export const getRouteArticleDetails = (id = ':id') => `/articles/${id}` as const;
export const getRouteArticles = () => '/articles' as const;
export const getRouteProfile = (id = ':id') => `/profile/${id}` as const;
export const getRouteArticleEdit = (id = ':id') => `/articles/${id}/edit` as const;
export const getRouteAdmin = () => '/admin' as const;
export const getRouteArticleCreate = () => '/articles/new' as const;
export const getRouteMain = () => '/' as const;
export const getRouteForbidden = () => '/forbidden' as const;
export const getRouteAbout = () => '/about' as const;
export const getRouteNotFound = () => '*' as const;
